(define (problem welding-problem) (:domain welding-top)
(:objects
    joint1 joint2 joint3 joint4 joint5 joint6 joint7 joint8 joint9 joint10 joint11 joint12 joint13 joint14 joint15 joint16 joint17 joint18 joint19 joint20 - joint
    pos1 - position
)

(:init
    (at pos1)

    (not_executed)

    (not_executing)

    (= (avg_joints_per_group) 20)

    (depends_on joint2 joint1)
    (depends_on joint3 joint1)
    (depends_on joint4 joint1)
    (depends_on joint5 joint1)
    (depends_on joint5 joint2)
    (depends_on joint5 joint3)
    (depends_on joint5 joint4)
    (depends_on joint7 joint6)
    (depends_on joint8 joint6)
    (depends_on joint9 joint6)
    (depends_on joint10 joint6)
    (depends_on joint10 joint7)
    (depends_on joint10 joint8)
    (depends_on joint10 joint9)
    (depends_on joint12 joint11)
    (depends_on joint13 joint11)
    (depends_on joint14 joint11)
    (depends_on joint15 joint11)
    (depends_on joint15 joint12)
    (depends_on joint15 joint13)
    (depends_on joint15 joint14)
    (depends_on joint17 joint16)
    (depends_on joint18 joint16)
    (depends_on joint19 joint16)
    (depends_on joint20 joint16)
    (depends_on joint20 joint17)
    (depends_on joint20 joint18)
    (depends_on joint20 joint19)
    (reachable_at joint1 pos1)
    (reachable_at joint2 pos1)
    (reachable_at joint3 pos1)
    (reachable_at joint4 pos1)
    (reachable_at joint5 pos1)
    (reachable_at joint6 pos1)
    (reachable_at joint7 pos1)
    (reachable_at joint8 pos1)
    (reachable_at joint9 pos1)
    (reachable_at joint10 pos1)
    (reachable_at joint11 pos1)
    (reachable_at joint12 pos1)
    (reachable_at joint13 pos1)
    (reachable_at joint14 pos1)
    (reachable_at joint15 pos1)
    (reachable_at joint16 pos1)
    (reachable_at joint17 pos1)
    (reachable_at joint18 pos1)
    (reachable_at joint19 pos1)
    (reachable_at joint20 pos1)
    (not_welded joint1)
    (not_welded joint2)
    (not_welded joint3)
    (not_welded joint4)
    (not_welded joint5)
    (not_welded joint6)
    (not_welded joint7)
    (not_welded joint8)
    (not_welded joint9)
    (not_welded joint10)
    (not_welded joint11)
    (not_welded joint12)
    (not_welded joint13)
    (not_welded joint14)
    (not_welded joint15)
    (not_welded joint16)
    (not_welded joint17)
    (not_welded joint18)
    (not_welded joint19)
    (not_welded joint20)
)

; (:goal
;     ;todo: put the goal condition here
;     (and 
;         (welded joint1)
;         (welded joint2)
;         (welded joint3)
;         (welded joint4)
;         (welded joint5)
;         (welded joint6)
;         (welded joint7)
;         (welded joint8)
;         (welded joint9)
;         (welded joint10)
;         (welded joint11)
;         (welded joint12)
;         (welded joint13)
;         (welded joint14)
;         (welded joint15)
;         (welded joint16)
;         (welded joint17)
;         (welded joint18)
;         (welded joint19)
;         (welded joint20)
;     )
; )

;un-comment the following line if metric is needed
;(:metric minimize (???))
)
