bottom_planner/transit:
  ros__parameters:
    plugins:
      - jigless_planner_transit_bt_node
bottom_planner/weld:
  ros__parameters:
    plugins:
      - jigless_planner_weld_bt_node
bottom_planner/validate:
  ros__parameters:
    plugins:
      - jigless_planner_validate_bt_node
top_planner/command_1:
  ros__parameters:
    plugins:
      - jigless_planner_command_bt_node
top_planner/command_2:
  ros__parameters:
    plugins:
      - jigless_planner_command_bt_node
top_planner/command_3:
  ros__parameters:
    plugins:
      - jigless_planner_command_bt_node
top_planner/move_robot:
  ros__parameters:
    plugins:
      - jigless_planner_moverobot_bt_node
top_planner/set_status_1:
  ros__parameters:
    plugins:
      - jigless_planner_setstatus_bt_node
top_planner/set_status_2:
  ros__parameters:
    plugins:
      - jigless_planner_setstatus_bt_node
top_planner/set_status_3:
  ros__parameters:
    plugins:
      - jigless_planner_setstatus_bt_node
top_planner/set_status_4:
  ros__parameters:
    plugins:
      - jigless_planner_setstatus_bt_node
top_planner/set_status_5:
  ros__parameters:
    plugins:
      - jigless_planner_setstatus_bt_node
