transit:
  ros__parameters:
    plugins:
      - jigless_planner_transit_bt_node
weld:
  ros__parameters:
    plugins:
      - jigless_planner_weld_bt_node
validate:
  ros__parameters:
    plugins:
      - jigless_planner_validate_bt_node
command_joint_1:
  ros__parameters:
    plugins:
      - jigless_planner_command_bt_node
command_joint_2:
  ros__parameters:
    plugins:
      - jigless_planner_command_bt_node
command_joint_3:
  ros__parameters:
    plugins:
      - jigless_planner_command_bt_node
moverobot:
  ros__parameters:
    plugins:
      - jigless_planner_moverobot_bt_node
set_status_1:
  ros__parameters:
    plugins:
      - jigless_planner_setstatus_bt_node
set_status_2:
  ros__parameters:
    plugins:
      - jigless_planner_setstatus_bt_node
set_status_3:
  ros__parameters:
    plugins:
      - jigless_planner_setstatus_bt_node
set_status_4:
  ros__parameters:
    plugins:
      - jigless_planner_setstatus_bt_node
set_status_5:
  ros__parameters:
    plugins:
      - jigless_planner_setstatus_bt_node

