transit:
  ros__parameters:
    plugins:
      - jigless_planner_transit_bt_node
weld:
  ros__parameters:
    plugins:
      - jigless_planner_weld_bt_node
validate:
  ros__parameters:
    plugins:
      - jigless_planner_validate_bt_node