workpieces:
  joint1: ["workpiece1", "workpiece2"]
  joint2: ["workpiece1", "workpiece2"]
  joint3: ["workpiece1", "workpiece2"]
  joint4: ["workpiece1", "workpiece3"]
  joint5: ["workpiece1", "workpiece3"]
  joint6: ["workpiece1", "workpiece3"]
  joint7: ["workpiece1", "workpiece4"]
  joint8: ["workpiece1", "workpiece4"]
  joint9: ["workpiece1", "workpiece4"]
  joint10: ["workpiece1", "workpiece4"]
  joint11: ["workpiece1", "workpiece5"]
  joint12: ["workpiece1", "workpiece5"]
  joint13: ["workpiece1", "workpiece5"]
  joint14: ["workpiece2", "workpiece6"]
  joint15: ["workpiece2", "workpiece6"]
  joint16: ["workpiece2", "workpiece6"]
  joint17: ["workpiece2", "workpiece6"]
  joint18: ["workpiece6", "workpiece7"]
  joint19: ["workpiece6", "workpiece7"]
  joint20: ["workpiece6", "workpiece7"]